config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :suits do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :suit
  belongs_to :user

  validate :start_date_cannot_be_in_the_past
  validate :end_date_cannot_be_before_start_date
  validates :status, presence: true, inclusion: { in: %w[Ordered Approved Shipped Delivered] }
  validates :start_date, presence: true
  validates :end_date, presence: true

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_cannot_be_before_start_date
    if end_date < start_date
      errors.add(:end_date, "can't be in the past")
    end
  end
end

app/models/suit.rb
class Suit < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

 validates :name, presence: true
 validates :size, presence: true
 validates :colour, presence: true
 validates :style, presence: true
 validates :occasion, presence: true, inclusion: { in: %w(Interview Funeral Wedding Party Date Prom) }
 validates :price, presence: true
 validates :brand, presence: true

 include PgSearch::Model
 pg_search_scope :search_form,
    against: [ :name, :occasion, :size, :colour, :style, :price, :brand],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :suits, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @suit = Suit.find(params[:suit_id])
  end

  def create
    @suit = Suit.find(params[:suit_id])
    @booking = Booking.new(booking_params_new)
    @booking.user = current_user
    @booking.suit = @suit
    @booking.total_cost = (@booking.end_date - @booking.start_date).to_i * @suit.price
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)

    redirect_to booking_path(@booking), notice: "Booking was updated"
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to bookings_path, notice: "Booking was destroyed"
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date)
    #remove :status permit, as it should be defaulted to "ordered"
  end

  def booking_params_new
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/suits_controller.rb
class SuitsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @pagy, @suits = pagy(Suit.search_form(params[:query].order(name: :asc)), items: 15)
    else
      @pagy, @suits = pagy(Suit.all.order(name: :asc), items: 15)
    end
  end

  def new
    @suit = Suit.new
  end

  def show
    @suit = Suit.find(params[:id])
  end

  def edit
    @suit = Suit.find(params[:id])
  end

  def update
    @suit = Suit.find(params[:id])
    if @suit.update(suit_params)
      redirect_to @suit, notice: 'Suit was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @suit = Suit.find(params[:id])
    @suit.destroy
    redirect_to suits_url, notice: 'Suit was successfully destroyed.'
  end

  def create
    @suit = Suit.new(suit_params)
    @suit.user = current_user
    if @suit.save!
      redirect_to suit_path(@suit)
    else
      render :new
    end
  end

  private

  def suit_params
    params.require(:suit).permit(:size, :colour, :style, :occasion, :price, :brand, :name, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/bookings/edit.html.erb
<div class="container">
  <h1>Edit your booking</h1>

  <div class="style-form">
    <div class="form">
      <%= simple_form_for [ @suit, @booking ] do |f| %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.input :status, as: :radio_buttons, input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item',
                    collection: ["Ordered", "Approved", "Shipped", "Delivered"]%>
        <%= f.submit "Submit", class: "btn btn-orange" %>
      <% end %>
    </div>
  </div>
  <div class="navigation">

    <p><%= link_to booking_path(@booking), class: "btn btn-gray" do%>
      <i class="fas fa-arrow-circle-left"></i><span> Back</span>
    <% end %>
    </p>
  </div>
</div>

app/views/bookings/index-copy-old.html.erb
index-copy-old.html.erb

app/views/bookings/index.html.erb
<!-- create a header and add a nav bar -->
<div class="container">
  <div>
    <h1> Booking Overview </h1>
  </div>

  <div class="container">
    <h3> Suits I'm Borrowing </h3>
    <% @bookings.each do |booking| %>
      <% if booking.user_id == current_user.id %>
        <div class="card-product">
          <img src="https://pngimg.com/uploads/suit/suit_PNG93235.png" />
          <div class="card-product-infos">
            <h2><%= booking.suit.name %></h2>
            <p>Status: <%= booking.status  %></p>
            <p>Suit will be lent between <em><%= booking.start_date %></em> and <em><%= booking.end_date %></em></p>
            <p> </p>
            <div class="d-flex booking-btns">
              <%= link_to "Show details", booking, class: "btn btn-orange mr-5" %>
              <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-gray mr-1" %>
              <%= link_to 'Delete booking', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-gray" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="container mt-5">
    <h3> Suits I'm Lending </h3>
    <% @bookings.each do |booking| %>
      <% if booking.suit.user_id == current_user.id  %>
        <div class="card-product">
          <img src="https://pngimg.com/uploads/suit/suit_PNG93235.png" />
          <div class="card-product-infos">
            <h2><%= booking.suit.name %></h2>
            <p>Status: <%= booking.status  %></p>
            <p>Suit will be lent between <em><%= booking.start_date %></em> and <em><%= booking.end_date %></em></p>
            <div class="d-flex booking-btns">
              <%= link_to "Show details", booking, class: "btn btn-orange mr-5" %>
              <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-gray mr-1" %>
              <%= link_to 'Delete booking', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-gray" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="navigation-bar mt-3">
    <p><%= link_to root_path, class:"btn btn-gray" do%> <i class="fas fa-arrow-circle-left"></i><span> Back to homepage</span>
    <% end %> </p>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="form">
    <%= simple_form_for [ @suit, @booking ] do |f| %>
      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
      <%= f.submit "Submit", class: "btn btn-orange" %> <%= link_to suit_path(@suit), class:"btn btn-gray" do%> <i class="fas fa-arrow-circle-left"></i><span> Back </span>
    <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container ">
  <div>
    <div class="order-details">
      <p>Status: <%= @booking.status %></p>
      <p>Start date: <%= @booking.start_date %> </p>
      <p>End date: <%= @booking.end_date %> </p>
      <p>Price: £<%= @booking.total_cost %></p>
    </div>
    <div class="navigation">
      <p><%= link_to "Edit", edit_booking_path(@booking), class: "btn btn-orange" %> <%= link_to "Delete", booking_path(@booking), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-orange" %> <%= link_to "Back", bookings_path, class: "btn btn-orange" %></p>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="navbar fixed-top navbar-lewagon navbar-collapse">
  <div class="main-logo d-flex align-self-stretch">
    <%= link_to root_path, class: "d-flex" do %>
      <img id="logo" src="https://pngimg.com/uploads/suit/suit_PNG93235.png"height="40px">
      <h3 class="logo-text"> SuitsYou </h3>
    <% end %>
  </div>
<!--    <div class="right-icons"> -->
    <div class="header-main-logo d-flex align-self-stretch align-items-center justify flex-equal">
      <div class="search-module d-flex flex-column align-self-stretch">
         <%= form_tag suits_path, method: :get, class: "d-flex" do %>
           <%= text_field_tag :query,
             params[:query],
             class: "form-control",
           placeholder: "Find a suit"
           %>
           <%= submit_tag "Go!", class: "btn btn-orange" %>
         <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="align-self-stretch d-flex flex-equal">
        <%= link_to 'Browse Suits', suits_path, class: "btn btn-gray" %>
        <div class="nav-item dropdown">
          <%= image_tag "https://4.imimg.com/data4/CQ/WI/MY-2290515/stylish-mens-suits-500x500.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Lend A Suit", new_suit_path, class: "dropdown-item" %>
            <%= link_to "My Profile", "#", class: "dropdown-item" %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
       </div>
    <% else %>
       <div class="justify-content-end align-self-stretch d-flex flex-equal">
          <%= link_to 'Browse Suits', suits_path, class: "btn btn-gray" %>
          <%= link_to 'Login', new_user_session_path, class: "btn btn-orange" %>
      </div>
    <% end %>
<!--     </div> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuitsYou | Suits for days.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "layouts/nav"%>
    <div class="pt-5 full-page">
      <%= yield %>
    </div>
    <footer id="main-footer">
      <div class="social-media">
        <a href="#" class="fab fa-facebook"></a>
        <a href="#" class="fab fa-twitter"></a>
        <a href="#" class="fab fa-linkedin"></a>
      </div>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img style="object-fit: cover" width="100%" height="100%", style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1426523038054-a260f3ef5bc9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2832&q=80)" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
      <div class="carousel-caption d-none d-md-block">
        <h1 class="shadowed"><strong>SuitsYou</strong> doesn't make you a <strong>CEO</strong> but it sure<strong> does help you look like one</strong>!</h1>
        <p class="shadowed">Change your life by discovering the countless styles you can try.</p>
        <p><%= link_to 'Browse Suits', suits_path, class: "btn btn-primary btn-lg" %></p>
      </div>
    </div>

    <div class="carousel-item">
    <img style="object-fit: cover" width="100%" height="600px" object-fit="cover" src="https://images.unsplash.com/photo-1425421669292-0c3da3b8f529?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1349&q=80" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
      <div class="carousel-caption d-none d-md-block">
        <h1 class="text-left"><strong>Snap backs</strong> and tattoos?<strong> No Honey.</strong> Good job and <strong>nice suits</strong>!</h1>
        <p>Log in to begin your journey.</p>
        <%= link_to 'Login', new_user_session_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <div class="carousel-item">
      <img style="object-fit: cover" width="100%" height="600px" src="https://images.unsplash.com/photo-1611943574626-91c9be96abc6?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1218&q=80" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
      <div class="carousel-caption d-none d-md-block">
        <h1><strong>Dress</strong> like you're going<strong>somewhere better later</strong>!</h1>
        <p>Start right now by booking a suit with us.</p>
        <%= link_to 'Book a suit', new_user_session_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
     </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4">
      <img class="bd-placeholder-img rounded-circle" style="object-fit: cover" width="140" height="140" src="https://webstockreview.net/images/1-clipart-transparent-2.png" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>

      <h2>Browse</h2>
      <p>Find  your dream suit</p>
      <p><%= link_to 'View details', suits_path, class: "btn btn-secondary" %></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="bd-placeholder-img rounded-circle" style="object-fit: cover" width="140" height="140" src="https://i.imgur.com/FL0SG2s.png" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>

      <h2>Sign up</h2>
      <p>Create an account on SuitsYou</p>
      <p><%= link_to 'View details', suits_path, class: "btn btn-secondary"%></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="bd-placeholder-img rounded-circle" style="object-fit: cover" width="140" height="140" src="https://toppng.com/uploads/preview/white-number-3-in-orange-circle-11552783230zi7ci6abv7.png" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>

      <h2>Book</h2>
      <p>Pay and reserve it with just one click</p>
      <p><%= link_to 'View details', suits_path, class: "btn btn-secondary"%></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">It made me feel very confident and presentable. <span class="text-muted">It has made my day.</span></h2>
      <p class="lead">“I don’t wear suits very often but thanks to SuitsYou I managed to rent one for a job interview. It made me feel very confident and presentable.  Highly recommend if you don’t want to spend money on something you only wear once.”</p>
    </div>
    <div class="col-md-5">
      <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://images.unsplash.com/photo-1558222218-b7b54eede3f3?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=634&q=80" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 order-md-2">
      <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
      <p class="lead">“ 2 weeks ago I met with a new investor to talk about my new business. The meeting was so last minute that I didn’t have time to go and look for a new suit. Luckily, a friend recommended SuitsYou and in less than 2h I managed to find something, book it and have it delivered to my front door. And guess what? I managed to convince the investor my idea would be profitable and he’s on board. Thank you SuitsYou for such a great and quick service!”</p>
    </div>
    <div class="col-md-5 order-md-1">
      <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://images.unsplash.com/photo-1521341057461-6eb5f40b07ab?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Such a clever idea! <span class="text-muted">Checkmate.</span></h2>
      <p class="lead">“I was meeting this girl at my favourite restaurant and as first impression matters, especially on your first date, I really needed something to show my style and possibly get her attention. Safe to say I never looked better! I’ve become addicted to this website as you never run out of choices.  Such a clever idea!”</p>
    </div>
    <div class="col-md-5">
      <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://images.unsplash.com/photo-1599557755020-56b2cd6d2d6b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
    </div>
  </div>

  <hr class="featurette-divider">
</div>

app/views/suits/_form.html.erb
<div class="container">
  <div class="style-form">
    <div class="form">
      <%= simple_form_for(suit) do |f| %>
        <%= f.input :name, placeholder: "eg. Luxury slim-fit suit perfect for big occassions!" %>
        <%= f.input :size %>
        <%= f.input :colour, as: :radio_buttons, input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item', collection: ["Black", "Blue", "Brown", "Green", "Grey", "Navy", "Tan", "White", "Other"] %>
        <%= f.input :style, placeholder: "eg. Slim-fit, tuxedo, double-breasted" %>
        <%= f.input :occasion, as: :radio_buttons, input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item',
                  collection: ["Interview", "Wedding", "Party", "Date", "Funeral", "Prom"]%>
        <%= f.input :price, label: "Price per day" %>
        <%= f.input :brand %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Submit", class: "btn btn-orange" %>
      <% end %>
    </div>
  </div>
</div>

<!-- In css, next .style-form and then use selectors -->

app/views/suits/edit.html.erb
<div class="container">
  <h1>Edit a Suit</h1>
  <div class="form">
    <%= render "form", suit: @suit %>
    <div class="navigation">
      <p> <%= link_to 'Show', @suit, class:"btn btn-orange"%> <%= link_to suits_path, class:"btn btn-gray" do%> <i class="fas fa-arrow-circle-left"></i><span> Back to suits</span>
    <% end %> </p>
    </div>
  </div>
</div>

app/views/suits/index.html.erb
<div class="container">
   <div class="top-page">
     <h1>Suits</h1>
      <div class="navigation">
        <p><%= link_to 'New Suit', new_suit_path, class: "btn btn-orange" %></p>
      </div>
   </div>

  <div class="pagination">
    <%== pagy_bootstrap_nav(@pagy).html_safe %>
  </div>

  <div class="container d-inline">
    <div class="cards">
      <% @suits.each do |suit| %>
        <div class="card">
        <%= link_to suit do %>
           <div class="card-body">
            <% if suit.photos.first %>
              <%= cl_image_tag suit.photos.first.key, class: "card-img-top" %>

            <% else %>
               <img src="https://images.unsplash.com/photo-1572325879775-5e8f8b20439f?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" class="card-img-top">
              <% end %>

            <h5><%= suit.name %></h5>
              <div id="card-details">
              <p>£<%= suit.price %> per day</p>
              <p><%= suit.brand %></p>
              <p>Size: <%=suit.size %> </p>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <!-- <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Brand</th>
          <th>Price</th>
          <th>Style</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @suits.each do |suit| %>
          <tr>
            <td><%= suit.name %></td>
            <td><%= suit.brand %></td>
            <td><%= suit.price %></td>
            <td><%= suit.style  %></td>
            <td><%= link_to 'Show', suit %></td>
            <td><%= link_to 'Edit', edit_suit_path(suit) %></td>
            <td><%= link_to 'Destroy', suit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table> -->
  </div>
<div class="pagination">
  <%== pagy_bootstrap_nav(@pagy).html_safe %>
</div>

  <div class="navigation">
    <p><%= link_to 'New Suit', new_suit_path, class: "btn btn-orange" %> <%= link_to root_path, class: "btn btn-gray" do%> <i class="fas fa-arrow-circle-left"></i><span> Back to homepage</span>
    <% end %> </p>
  </div>
</div>

app/views/suits/new.html.erb
<div class="container ">
  <h1>Create a suit</h1>
  <div class="container">
    <div class="form">
      <%= render "form", suit: @suit %>
      </div>
      <div class="navigation">
        <p id="back-button"><%= link_to suits_path, class: "btn btn-gray" do%> <i class="fas fa-arrow-circle-left"></i><span> Back</span>
        <% end %> </p>
    </div>
  </div>

</div>

app/views/suits/show.html.erb
<div class="container">
  <div class="top-page">
    <h1> <%= @suit.name %> </h1>
    <div class="navigation">
      <p><%= link_to 'Book this suit', new_suit_booking_path(@suit), class:"btn btn-orange" %> </p>
    </div>
  </div>
  <div class="bordered-container">
    <div id="suits-details">
      <h5>Price: £<%= @suit.price %> per day</h5>
      <p>Brand: <%= @suit.brand %></p>
      <p>Size: <%= @suit.size %> </p>
      <p>Colour: <%= @suit.colour %></p>
      <p>Style: <%= @suit.style %></p>
      <p>Great for: <%= @suit.occasion %></p>
    </div>
    <div class="carousel">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @suit.photos.each_with_index do |photo, index|  %>
            <% if index == 0 %>
              <div class="carousel-item active">
                <%= cl_image_tag photo.key, class:"d-block" %>
              </div>
            <% else %>
                <div class="carousel-item">
                  <%= cl_image_tag photo.key, class:"d-block" %>
                </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>

  <div class="navigation">
    <p><%= link_to 'Book this suit', new_suit_booking_path(@suit), class:"btn btn-orange" %> <%= link_to 'Delete', suit_path(@suit), method: :delete, class:"btn btn-orange"%> <%= link_to 'Edit', edit_suit_path, class:"btn btn-orange" %> </p>
    <p><%= link_to suits_path, class:"btn btn-gray" do%> <i class="fas fa-arrow-circle-left"></i><span> Back to suits</span>
    <% end %> </p>
  </div>
</div>